CREATE DATABASE customer_behaviour;
USE customer_behaviour;

-- Q1) What is total revenue generated by male vs female customers
		
        SELECT gender, SUM(purchase_ammount)
		FROM customers
		GROUP BY (gender);
        
-- Q2) Which customer used discount bill but still spent more than the average purchase ammount

		SELECT customer_id, purchase_ammount
        FROM customers
        WHERE discount_applied = 'Yes' AND purchase_ammount >= (SELECT AVG(purchase_ammount) FROM customers); 
        
-- Q3) Which are the Top 5 products with the highest average review rating
		
        SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
        FROM customers
        GROUP BY item_purchased
        ORDER BY AVG(review_rating) DESC
        LIMIT 5;
        
-- Q4) Compare the average purchase ammount between the Standard and express shipping

		SELECT shipping_type, ROUND(AVG(purchase_ammount),2) AS "Average Purchase Ammount"
        FROM customers
        WHERE shipping_type IN ('Standard', 'Express')
        GROUP BY (shipping_type);
        
-- Q5) Do subscribed customers spend more ? compare average spend and revenue between subscribers and non subscribers

		SELECT  subscription_status,
        COUNT(customer_id) AS "Total Customers",
        ROUND(AVG(purchase_ammount),2) AS "Average Spend",
        ROUND(SUM(purchase_ammount),2) AS "Total Revenue"
        FROM customers
        GROUP BY subscription_status
        ORDER BY "Total Revenue", "Average Spend" DESC;
        
-- Q6) Which 5 products have the highest percentage of purchases with discount applied ?
        
		SELECT 
				item_purchased,
				ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS `discount rate`
		FROM customers
		GROUP BY item_purchased
		ORDER BY `discount rate` DESC
		LIMIT 5;
        
-- Q7) segment the customers into New, Returning, Loyal based on their total number of previous purchases and show the count of each segment

		WITH customer_type AS (
		SELECT 
			customer_id, 
			previous_purchases,
			CASE 
				WHEN previous_purchases = 1 THEN 'New'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal'
			END AS customer_segment
		FROM customers
		)
		SELECT 
			customer_segment, 
			COUNT(*) AS `Number of customers`
		FROM customer_type
		GROUP BY customer_segment
		ORDER BY `Number of customers` DESC;	

-- Q8) What are the top 3 most purchased products within each category

		WITH item_counts AS (
			SELECT 
				category,
				item_purchased,
				COUNT(customer_id) AS total_orders,
			ROW_NUMBER() OVER(
				PARTITION BY category 
				ORDER BY COUNT(customer_id) DESC
			) AS item_rank
			FROM customers
			GROUP BY category, item_purchased
			)	
			SELECT 
				category, 
				item_purchased, 
				total_orders, 
				item_rank
			FROM item_counts
			WHERE item_rank <= 3;
            
-- Q9) Are customers who are repeats buyers (more than 5 previous purchases) also likely to describe?

		SELECT subscription_status,
        COUNT(customer_id) AS 'repeat buyers'
        FROM customers
        WHERE previous_purchases >5
        GROUP BY subscription_status;
        
        
-- Q10) What is the revenue generation of each age group

		SELECT 
			age_group,
			SUM(purchase_ammount) AS Total_Revenue
		FROM customers
		GROUP BY age_group
		ORDER BY Total_Revenue DESC;
        